### ISSUE TITLE
_check_duplicates may be uninitialized

### ISSUE THREAD

**Issue by saily** [bluedynamics/node.ext.ldap#10]
See traceback attached:

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module my.package.api.base, line 100, in decorator
      Module my.package.api.basket, line 216, in basket_overview
      Module my.package.api.basket, line 192, in _get_basket
      Module my.sap.package.utility, line 75, in call_service
      Module my.package.utility, line 64, in get_payloads
      Module my.package.utility, line 61, in user_partner_nr
      Module my.package.utility, line 53, in user_sapdata
      Module plumber._instructions, line 385, in entrance
      Module node.behaviors.nodespace, line 39, in __getitem__
      Module node.ext.ldap._node, line 221, in __getitem__
      Module node.ext.ldap._node, line 624, in _load_keys
    AttributeError: 'LDAPNode' object has no attribute '_check_duplicates

Seems `props` was not True, so [this](https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/_node.py#L198) was not executed. We should provide a default value anyway, but would be interesting how this could happen.

**Comment by rnixx** [comment]
This happens for child nodes https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/_node.py#L192. And it looks like you have entries in your LDAP where values of parts of the DN actually not equals the corresponding value in the related record.

**Comment by jensens** [comment]
``self._check_duplicates`` should be initialized in any case at ``__init__`` here https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/_node.py#L167

**Comment by rnixx** [comment]
True

**Comment by rnixx** [comment]
LDAPNode._load_keys has been removed. This function was the only place where check_duplicates was used. So check_duplicates has been removed as well
