### ISSUE TITLE
limit number of rows returned by search()

### ISSUE THREAD

**Issue by zopyx** [bluedynamics/node.ext.ldap#20]
Is there a parameter to limit the number of returned results of search() or is this subject to the underlaying code calling search()?

**Comment by jensens** [comment]
If a page_size is configured/given it is used (but this is meant for LDAP configuration, not as batching api).

So answer is: No limit at the moment. It would be a useful feature.

Implementation would need to switch to [search_ext](https://www.python-ldap.org/doc/html/ldap.html#ldap.LDAPObject.search_ext) and use the ``sizelimit`` parameter.

**Comment by zopyx** [comment]
page_size is it.

I was checking for 'max' and 'limit'.
