### ISSUE TITLE
Improper escaping of \2c 

### ISSUE THREAD

**Issue by zopyx** [bluedynamics/node.ext.ldap#26]
See screenshot.

An LDAP entry contains a comma correctly escaped as \2c (because the comma is part of the 
organization unit).

The related entry (coming from a ldap_session.search() query) shows up in Python as \\c with another backslash. No encoding conversions taking place on my side. You see that the string in Python is a str encoded as utf-8.  The correct conversion of "\2c" from LDAP to Python would be "\,".

In contrast: reading a related node containing \2c in its DN through the LDAPNode API results in a DN attribute with the escaped command translated to "\," 

The conversion on the LDAPNode level appears correct but the first case appears like an error.

![screenshot 2016-11-07 13 30 46](https://cloud.githubusercontent.com/assets/594239/20057946/9daf9178-a4ee-11e6-8e6c-e407b33a110f.png)

**Comment by jensens** [comment]
Do I get it right if I say the double backslash should convert to a single (and vice versa probably as well)? So in utf8 there is a ``\2c`` which is in fact the ``,``?

**Comment by zopyx** [comment]
I am really unsure what the right behavior would be. At least at the moment
the behavior for search() and LDAPNode appears different. In my case I had
to match a data coming from a search() against those represented as an
LDAPNode and due to the different behavior it took a while find the problem
here. In particular I had a person node with a link to a department (by its
DN). This department DN contained \2c but represented on the LPADNode level
as \, . So it was impossible to use this _different_ for an LDAP search for
finding the department.

2016-11-07 20:40 GMT+01:00 Jens W. Klein <notifications@github.com>:

**Comment by rnixx** [comment]
Please reopen if #38 did not fix the problem
