### ISSUE TITLE
Switch off referrals when connecting to Active Directory

### ISSUE THREAD

**Issue by rnixx** [bluedynamics/node.ext.ldap#30]
From https://github.com/collective/pas.plugins.ldap/issues/37

Q: My script bound to MS Active Directory but a a search operation results in an exception ldap.OPERATIONS_ERROR with the diagnostic messages text "In order to perform this operation a successful bind must be completed on the connection.".
    What's happening here?

A: When searching from the domain level MS AD returns referrals (search continuations) for some objects to indicate to the client where to look for these objects. Client-chasing of referrals is a broken concept since LDAPv3 does not specify which credentials to use when chasing the referral. Windows clients are supposed to simply use their Windows credentials but this does not work in general when chasing referrals received from and pointing to arbitrary LDAP servers.
Therefore per default libldap automatically chases the referrals internally with an anonymous access which fails with MS AD.

So best thing is to switch this behaviour off:

      l = ldap.initialize('ldap://foobar')
      l.set_option(ldap.OPT_REFERRALS,0)

**Comment by alexsielicki** [comment]
I'm happy to make this change in the code, but I have no idea how to check if we are connected to Active Directory. Can anyone help steer me in the right direction here? Had to hard code this in my code as a temporary fix, but want to do this correctly soon. Thanks!

**Comment by rnixx** [comment]
Since this is a broken concept we can turn referrals off by default IMHO.

This needs to be done here

https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/base.py#L84

It may be a good idea to have a config flag on LDAP properties (passed to LDAP connector) defining whether referrals are enabled if someone really needs them for some reason.

**Comment by alexsielicki** [comment]
Just made a pull request with a fix.

Wondering if this also needs to be done here:
https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/session.py#L73
Because there's a call to ldap.initialize

**Comment by rnixx** [comment]
@alexsielicki nice catch, yes, please also set the option there. Thank you!

**Comment by alexsielicki** [comment]
Just set the option in https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/session.py#L73 too
