### ISSUE TITLE
Are there plans for python 3 support?

### ISSUE THREAD

**Issue by do3cc** [bluedynamics/node.ext.ldap#33]
It seems the dependency python-ldap will be python2 only for the foreseeable future, while pyldap provides a backward compatible fork that also works with python3. I didn't check the other dependencies.

**Comment by rnixx** [comment]
Hi Patrick,

Actually - yes - there are plans for porting to python3. The dependency packages already are ported.
But - no - we have no idea when this happens.

-r

**Comment by jensens** [comment]
As this library lives from its contributions in form of time and work, or money, this primary depends on this. At some point, we will have projects ourselves to upgrade, but at the moment at least from my projects, there are no LDAP needs.

I think it is very straightforward to port this package to a different LDAP library.

Most base logic (where ``ldap`` is imported) is in
- https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/base.py (connection creation, options, exception handling, more specific tasks)

With some minor usage in 
- https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/session.py#L78-L85 (connection creation again (?), options, exceptions)
- https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/scope.py (only redeclarations)
- https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/schema.py#L18-L30 (LDAP schema specifics)
- https://github.com/bluedynamics/node.ext.ldap/blob/master/src/node/ext/ldap/ugm/_api.py (only exception handling)

**Comment by do3cc** [comment]
Thanks for your quick replies!
I also think it won't be hard, but will defer to work on it for now too.

**Comment by rnixx** [comment]
hard != hard. While adopting the underlying lib won't be that much work (we can also consider to use ldap3 if it has some going for it, not evaluated yet), the main work porting all the other dependency libraries was to transform the doc tests into unit tests. You really don't want to maintain py2+py3 compatible doc tests. So even if porting is not "hard", it will be a lot of work.

**Comment by reinhardt** [comment]
I've started looking into this as part of the current Alpine City Sprint. @jensens, maybe you could give me write access, then I can soon push a branch with some first steps.

**Comment by reinhardt** [comment]
I've pushed a python3 branch with the basics. There are two remaining issues:

1. smbpasswd throws ```undefined symbol: PyString_FromStringAndSize``` on python 3
2. different attribute keys are returned on python 3, e.g. ```id``` instead of ```rdn```

Both are tricky to debug; the first because it's a C module, the second because of the plumbing stuff. I might need some help there.

**Comment by reinhardt** [comment]
P.S. It looks like ```PyString_FromStringAndSize``` has to be replaced with ```PyBytes_FromStringAndSize```. Not sure whether that's enough though.

**Comment by krissik** [comment]
> I've pushed a python3 branch with the basics. 

@reinhardt Thanks a lot! I started looking for python3 support for pas.plugins.ldap 15 minutes after your push :-)

>     1. smbpasswd throws `undefined symbol: PyString_FromStringAndSize` on python 3

I replaced smbpasswd with passlib: https://github.com/krissik/node.ext.ldap/commit/7d968aa85463c39373caec5241bf84bf7593f06d
It seems to work but I have no idea if there other impacts. What do you think about it?

**Comment by jensens** [comment]
If passlib works, I think this is the way to go. I used passlib in another project and it is a well maintained project. smbpasswd looks a bit abandoned.

**Comment by reinhardt** [comment]
FTR, porting smbpasswd was not too hard: https://github.com/barryp/py-smbpasswd/pull/3
But apart from that I can't say anything qualified about it and tend to agree with @jensens.

**Comment by rnixx** [comment]
python 3 support is merged via #44
