### ISSUE TITLE
Use ReconnectionLDAPObject to make creating the connection more robust

### ISSUE THREAD

**Issue by joka** [bluedynamics/node.ext.ldap#40]
Use ``ldap.ldapobject.ReconnectLDAPObject`` instead of ``SimpleLDAPObject`` to create
  the connection object. This makes creating/binding the connection more robust.
Use the exiting properties `retry_max` (default 1) and `retry_delay` (default 10) to configure the configure ``ReconnectLDAPObject``.

Implementation:  https://github.com/joka/node.ext.ldap/tree/use_reconnect_ldap_object

**Comment by jensens** [comment]
Thanks! Please create a Pull request, so we can merge your work.
