### ISSUE TITLE
LDAPNode.search_scope = SUBTREE is broken when the LDAP directory contains elements with the same RDN in different containers.

### ISSUE THREAD

**Issue by cluck** [bluedynamics/node.ext.ldap#5]
*LDAPNode.search_scope = SUBTREE* is broken when the LDAP directory contains elements with the same RDN in different containers.

E.g. if LDAP contains both:

        cn=admin,dc=example,dc=org
        cn=admin,ou=People,dc=example,dc=org

then this fails because both items are keyed by *cn=admin*. This should probably be *cn=admin* and *cn=admin,ou=People* instead.

        >>> base = LDAPNode(session.baseDN, props=props)
        >>> base.search_scope = node.ext.ldap.SUBTREE
        >>> base.search('(cn=admin)')
        ... Traceback (most recent call last):
        ...   File "/usr/local/lib/python2.7/dist-packages/plumber-1.2-py2.7.egg/plumber/_instructions.py", line 386, in entrance
        ...     return plumbing_method(_next, self, *args, **kw)
        ...   File "/usr/local/lib/python2.7/dist-packages/node-0.9.10-py2.7.egg/node/behaviors/nodespace.py", line 39, in __getitem__
        ...     return _next(self, key)
        ...   File "/usr/local/lib/python2.7/dist-packages/node.ext.ldap-0.9.4-py2.7.egg/node/ext/ldap/_node.py", line 220, in __getitem__
        ...     self._load_keys()
        ...   File "/usr/local/lib/python2.7/dist-packages/node.ext.ldap-0.9.4-py2.7.egg/node/ext/ldap/_node.py", line 623, in _load_keys
        ...     (self._key_attr, key))
        ... RuntimeError: Key not unique: rdn='cn=admin'.

**Comment by rnixx** [comment]
Should be fixed. See #13
