### ISSUE TITLE
`_login_attr` not set if `cfg.attrmap['login'] == cfg.attrmap['id']`

### ISSUE THREAD

**Issue by ale-rt** [bluedynamics/node.ext.ldap#55]
I do not understand why the code is not setting `_login_attr` if `cfg.attrmap['login'] == cfg.attrmap['id']`, see:
https://github.com/bluedynamics/node.ext.ldap/blob/ccf746d613811f7f7f9db17d589b1b5007f85ad5/src/node/ext/ldap/ugm/_api.py#L472-L474

IMO that should be set independently.

Not setting it has the side effect that the `id_for_login` method returns different ids for "admin" and "ADMIN", which I think it should not.

Related to https://github.com/collective/pas.plugins.ldap/issues/104

**Comment by rnixx** [comment]
Solved via 579fee7a811b312bb0a9f643c2bb91bcdab2ee1b

**Comment by ale-rt** [comment]
Thanks a lot!
