### ISSUE TITLE
DN comparison not case sensitive.

### ISSUE THREAD

**Issue by jensens** [bluedynamics/node.ext.ldap#58]
At 

https://github.com/bluedynamics/node.ext.ldap/blob/351d69747bd870e7b5a977f1f2c4a1373e3f04f0/src/node/ext/ldap/_node.py#L464 

The comparison is not case insensitive, but DNs are. The problem popped up at HU-Berlin, were the last part was "c=de" or "c=DE" which is ion fact schema wise both fine.

**Comment by rnixx** [comment]
Fixed via ea6c4adc03e687ba5427fcfcf6e9fd9cadf397fe
